[jenkins]
jenkins-server ansible_host=<JENKINS_IP> ansible_user=ec2-user

[monitoring]
monitoring-server ansible_host=<MONITORING_IP> ansible_user=ec2-user

[k8s-nodes]
k8s-node-1 ansible_host=<NODE1_IP> ansible_user=ec2-user
k8s-node-2 ansible_host=<NODE2_IP> ansible_user=ec2-user

[all:vars]
ansible_python_interpreter=/usr/bin/python3
aws_region=us-east-1
project_name=tictactoe